### ISSUE TITLE
implement `limit`

### ISSUE THREAD

**Issue by christianp** [mathjax/ctop#14]
http://www.w3.org/Math/testsuite/build/main/Content/SequencesAndSeries/limit/limit6-form.xhtml

**Comment by christianp** [comment]
I've put `limit` in, but it doesn't bracket the argument like the sample rendering does. Do we want this?

**Comment by davidcarlisle** [comment]
On 11 April 2014 14:15, Christian Perfect notifications@github.com wrote:

> I've put limit in, but it doesn't bracket the argument like the sample
> rendering does. Do we want this?
> 
> ## 

Of course the "safe but ugly" option is to bracket everything, so dropping
brackets is always slightly risky but I'd have thought that at least 1 and
probably 2 pairs of brackets in that sample image could be dropped so I
don't think you should strain to get exactly that choice of brackets if you
are getting less.

**Comment by pkra** [comment]
I'm with @davidcarlisle -- trying the MML test on https://rawgit.com/mathjax/ctop/master/tests/try-ctop.html I prefer the new rendering, @christianp .
