### ISSUE TITLE
Add options for stylistic choices

### ISSUE THREAD

**Issue by christianp** [mathjax/ctop#30]
e.g. should curl be `curl(a)` or `∇×a`?

**Comment by pkra** [comment]
Note to self. For the MathJax integration, we might want to consider @davidcarlisle's suggestion to prefer Presentation MML from annotation-xml elements -- if an author makes an effort to add a specific presentation, MathJax should probably honor it.

**Comment by davidcarlisle** [comment]
That suggestion isn't just mine: it is in the spec (although I may have written that bit:-)

http://www.w3.org/Math/draft-spec/chapter5.html#mixing.alternate.representations

> Note that when a presentation MathML annotation is present in a semantics element, it may be used as the default rendering of the semantics element, instead of the default rendering of the first child.

**Comment by christianp** [comment]
ctop.js does use annotation-xml, so I'm closing this.
